-- Add cooking_notes column to recipes table
-- This column stores AI-generated cooking tips and notes from the cooking assistant

ALTER TABLE recipes 
ADD COLUMN cooking_notes TEXT[];

-- Add comment to explain the column
COMMENT ON COLUMN recipes.cooking_notes IS 'Array of cooking tips and notes generated by the AI cooking assistant';

